---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-config
data:
  # Environment variables for Tailscale
  TS_USERSPACE: "false"
  TS_ROUTES: "10.0.3.0/24"
  TS_ACCEPT_DNS: "true"
  TS_AUTH_ONCE: "true"
  TS_HOSTNAME: "k8s-subnet-router"
  TS_EXTRA_ARGS: "--login-server=https://vpn.batk.me"
  TS_KUBE_SECRET: "tailscale-auth"
  SA_NAME: "tailscale-sa"
