apiVersion: apps/v1
kind: Deployment
metadata:
  name: tailscale-subnet-router
  namespace: tailscale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tailscale-subnet-router
  template:
    metadata:
      labels:
        app: tailscale-subnet-router
    spec:
      serviceAccountName: tailscale-sa
      containers:
        - name: tailscale
          image: tailscale/tailscale:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: AuthKey
          envFrom:
            - configMapRef:
                name: tailscale-config
          volumeMounts:
            - name: dev-net-tun
              mountPath: /dev/net/tun
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - 'tailscale status 2>/dev/null'
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 2
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - 'tailscale status 2>/dev/null'
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
