server_url: https://vpn.batk.me
listen_addr: 0.0.0.0:8080

policy:
  path: /etc/headscale/acl.hujson

noise:
  private_key_path: /var/lib/headscale/noise_private.key

tls_cert_path: ""
tls_key_path: ""

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
                
derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/db.sqlite

log:
  format: text
  level: info

dns:
  magic_dns: true
  base_domain: vpn-internal.batk.me

  # DNS for cluster applications
  extra_records:
    - name: "argocd.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "harbor.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "swagger.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "pihole.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "photos.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "vanilla.minecraft.batk.me"
      type: "A"
      value: "10.0.3.120"
    - name: "overseerr.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "jellyseerr.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "radarr.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "sonarr.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "prowlarr.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "bazarr.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "tautulli.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "torrent.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "jellyfin.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "lazylibrarian.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "calibre.media.batk.me"
      type: "A"
      value: "10.0.3.52"
    - name: "photos.batk.me"
      type: "A"
      value: "10.0.3.52"

  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8

  override_local_dns: false

disable_check_updates: true
