server_url: https://vpn.batk.me
listen_addr: 0.0.0.0:8080

policy:
  path: /etc/headscale/acl.hujson

noise:
  private_key_path: /var/lib/headscale/noise_private.key

tls_cert_path: ""
tls_key_path: ""

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

database:
  type: sqlite3
  sqlite:
    path: /var/lib/headscale/db.sqlite

log:
  format: text
  level: info

dns:
  magic_dns: true
  base_domain: vpn-internal.batk.me

  # DNS for cluster applications
  extra_records:
    - name: "*.batk.me"
      type: "A"
      value: "10.0.3.52"

  # nameservers:
  # global:
  # - 1.1.1.1
  # - 8.8.8.8

  override_local_dns: false

disable_check_updates: true
